import QueryProvider from "@/app/QueryProvider";
import { Toaster } from "react-hot-toast";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/app/styles/globals.css";
import { Footer, Navbar } from "./_components/commons";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <Navbar />
          <Toaster />
          {children}
          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
